---
title: Tanjun Media
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  work:
    title: Work
    output: true
    permalink: "/work/:path/"
  clients:
    title: clients
    output: true
  contents:
    title: contents
    output: true
  services:
    title: services
    output: true
  social:
    title: social
    output: true
defaults:
- scope:
    path: ''
    type: clients
  values:
    permalink: "/work/tag/:title/"
    layout: clients
- scope:
    path: ''
    type: services
  values:
    permalink: "/work/tag/:title/"
    layout: services
- scope:
    path: ''
    type: contents
  values:
    permalink: "/work/tag/:title/"
    layout: contents
email: hello@tanjunmedia.com
description: |-
  We are digital film content creators.

  We are digital natives We live and breathe social content.

  We make great stuff and tell great stories and we would love to help tell yours.
baseurl: 
url: http://www.tanjunmedia.com
markdown: kramdown
plugins:
- github-pages
twitter_username: tanjunmedia
facebook_username: tanjunmedia
instagram_username: tanjunmediauk
vimeo_username: tanjunmedia
address: |-
  UNIT 7, 1C SHELFORD PLACE
  LONDON, N16 9HS
office: '020 7684 9872 '
mobile: '078 5525 9898'
company_number: 10184325
