---
title: Tanjun Media
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  work:
    title: Work
    output: true
    permalink: "/work/:path/"
  clients:
    title: clients
    output: true
  services:
    title: services
    output: true
defaults:
- scope:
    path: ''
    type: clients
  values:
    permalink: "/work/tag/:title/"
    layout: clients
- scope:
    path: ''
    type: services
  values:
    permalink: "/work/tag/:title/"
    layout: services
email: hello@tanjunmedia.com
description: |-
  <b>Tanjun Media</b> are digital film content creators.
  We want to make great stuff and tell great stories and we would love to help tell yours.
about: We can do the lot! From the creative to the execution. We don't have fancy
  offices or account managers. This allows us to put all of your money on what people
  see on the screen. Where it counts.
baseurl: "/"
url: https://www.tanjunmedia.com
markdown: kramdown
plugins:
- github-pages
mailto_img: "/uploads/social1.png"
twitter_username: tanjunmedia
twitter_img: "/uploads/social4.png"
facebook_username: tanjunmedia
facebook_img: "/uploads/social2.png"
instagram_username: tanjunmediauk
instagram_img: "/uploads/social3.png"
vimeo_username: tanjunmedia
vimeo_img: "/uploads/social5.png"
address: |-
  UNIT 7, 1C SHELFORD PLACE
  LONDON, N16 9HS
office: '020 7684 9872 '
mobile: '078 5525 9898'
company_number: 10184325
reel: https://s3.eu-west-2.amazonaws.com/tanjun/hero
reel_vimeo_link: "//vimeo.com/425161762"
reel_vimeo_copy: Play 2020 Reel
