---
title: Tanjun Media
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  work:
    title: Work
    output: true
    permalink: "/work/:path/"
  clients:
    title: clients
    output: true
  contents:
    title: contents
    output: true
  services:
    title: services
    output: true
  social:
    title: social
    output: true
defaults:
- scope:
    path: ''
    type: clients
  values:
    permalink: "/work/tag/:title/"
    layout: clients
- scope:
    path: ''
    type: services
  values:
    permalink: "/work/tag/:title/"
    layout: services
- scope:
    path: ''
    type: contents
  values:
    permalink: "/work/tag/:title/"
    layout: contents
email: hello@tanjunmedia.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description. '
baseurl: ''
url: http://www.tanjunmedia.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
plugins:
- github-pages
